name: docs

on:
  push:
    branches:
      - docs-initial # temp switch to main 
    tags:
      # only run on tags for real releases and special docs releases
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-docs.[0-9]+'
    # tags-ignore:
    #   - "*rc*"
    #   - "*beta*"
    #   - "*alpha*"
    #   - "*test*"
    #   - "*dev*"

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: python:3.9
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Requirements
        run: pip install -r ./docs/requirements.txt
      - name: Build with MkDocs (validation)
        run: |
          mkdocs build --verbose --clean
          rm -r site/
      - name: Configure Git
        if: startsWith(github.ref, 'refs/tags/')
        id: git
        run: |
          git config --global user.name pipeline-container-desktop.io
          git config --global user.email pipeline@container-desktop.io
          echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Build & Deploy with Mike (versioned)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mike deploy --update-aliases --push --rebase ${{ steps.git.outputs.tag }} stable